# Script for backend implementation
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      # Scheme's name
      POSTGRES_DB: unozar

  adminer:
    image: adminer
    restart: always
    ports:
      - 8079:8080

  backend:
    image: unozar:0.0.1-SNAPSHOT
    depends_on:
      - db
    ports:
      - 8080:8080
    expose:
      - "8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/unozar
