# Script for backend implementation
# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes:
      - ./data:/var/lib/postgresql
    expose:
      - "5432"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB: unozar

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080
